### PR TITLE
Include country prefix when updating model value

### PR DESCRIPTION
**Pull request by michaelmcauley**
We are using this directive to allow users to input a telephone number, which is then saved to our database. In order for the number to re-display properly, we need to supply the prefix on subsequent page views so the directive will show the proper flag and format the number as expected.

This simple change force-includes the country prefix whenever updating the model value. This behavior could easily be made optional via a config flag.

### CODE REVIEW

**Comment by sovanna** [comment]
+1 merge it !

**Comment by LostCrew** [comment]
:+1:

**Comment by mareczek** [comment]
Could you please review the code for conflicts?

**Comment by rbrcurtis** [comment]
PR updated.

**Comment by michaelmcauley** [comment]
Closing this pull request; will resubmit fork from a personal branch instead of company owned repo

**Pull request closed without merging**
