### PR TITLE
Add skip utils to config

### PR DESCRIPTION
**Pull request by mrkmg**
Adds an option to ipnConfig to allow for global skip-util-script-download.

I include it globally in my app and do not want to muddy up all my tel input elements with the same attribute over and over

### CODE REVIEW

**Comment by skfd** [comment]
:+1:

**Comment by mrkmg** [comment]
I was not sure if my commit should include the changes integrated into the "release" folder. I erred on the safe side and did not generate the grunt tasks.

**Comment by mrkmg** [comment]
@mareczek Are you maintaining this project anymore?

**Comment by mareczek** [comment]
Sorry for the delay, I got stuck among our commercial work @ enginearch.com. The pull request looks legit. Merging right away!

**Pull request merged**
